services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - back-tier
    depends_on:
      - mongodb
  mongodb:
    env_file:
      - .env
    image: mongo:5.0.10
    networks:
      - back-tier
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb:/date/db
volumes:
  mongodb: {}
networks:
  back-tier: {}
